### ISSUE TITLE
Acceleration of Bubbles and Bullets

### ISSUE THREAD

**Issue by Evgeny608799** [ForNeVeR/O21#183]
In original game, when accelerating the submarine, bullets and particles also accelerate, **according to the direction** of acceleration and the **direction of movement of the object** (for example, if the submarine accelerates when surfacing, then new bubbles acquire this acceleration).

It also works in the opposite direction, meaning there may be a slight slowdown.

**Comment by ForNeVeR** [comment]
I think you mean not _acceleration_ but _initial velocity_. This is how it works in real physics as well: if you shoot a bullet while moving on train, your bullet gets initial velocity of train (plus whatever velocity you give to it when shooting).

Interestingly, in this game, the concept of _acceleration_ doesn't exist: you have several fixed velocity choices for player and fixed velocities for any moving object; nothing _accelerates_ or _decelerates_ technically; it just "switches gears" instantly.

The issue is a very valid one, yeah.
